version: "3.8"

services:
  lendify_app:
    build:
      context: .
    container_name: lendify_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_URL=http://localhost:8080